### ISSUE TITLE
help plz

### ISSUE THREAD

**Issue by miyazaki-2000** [Naatyu/MagNav#1]
bro ,i dont how to download Eastern_2.h5&Renfrew_2.h5 , could you tell me

**Comment by naatyu** [comment]
Hi !

Unfortunately, the authors have deleted the data from the original dataset. I was able to use these maps because I downloaded the dataset before they were deleted. As I'm not the owner of these maps, I can't share them with you, but perhaps you can try using the map of Canada (there's a link in the README). If you really need these maps, you can also try contacting the authors of the original dataset: [magnav-admins@mit.edu](mailto:magnav-admins@mit.edu).

I hope this helps!

**Comment by miyazaki-2000** [comment]
thanks
